# Generated by Django 5.2.6 on 2025-09-18 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.BigIntegerField(db_column='user_id')),
                ('category_id', models.BigIntegerField(db_column='category_id', verbose_name=django.db.models.deletion.DO_NOTHING)),
                ('created_by', models.BigIntegerField(db_column='created_by')),
                ('updated_by', models.BigIntegerField(db_column='updated_by')),
            ],
            options={
                'db_table': 'suggestions_text',
                'managed': True,
            },
        ),
    ]
