# Generated by Django 5.2.6 on 2025-10-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('suggestion', '0006_proposal_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='suggestion.proposal'),
        ),
    ]
