# Generated by Django 5.2.6 on 2025-10-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_permission_code_rolehaspermission_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rolehaspermission',
            options={'ordering': ['-assigned_at']},
        ),
    ]
