# Generated by Django 5.2.6 on 2025-10-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_alter_permission_options_alter_role_options_and_more'),
        ('permissions', '0004_initial_roles'),
    ]

    operations = [
    ]
