# Generated by Django 5.2.6 on 2025-10-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'عضو'), ('admin', 'ادمین'), ('owner', 'مالک')], default='member', max_length=20),
        ),
    ]
