# Generated by Django 5.2.6 on 2025-10-31 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_created_at_user_updated_at_user_updated_by_and_more'),
        ('suggestion', '0006_proposal_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProposalUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_proposals/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('original_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_uploads', to='suggestion.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_proposals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پاسخ مشاور')),
                ('file', models.FileField(blank=True, null=True, upload_to='consultant_replies/')),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_replies', to=settings.AUTH_USER_MODEL)),
                ('proposal_upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_reply', to='Accounts.userproposalupload')),
            ],
        ),
    ]
