# Generated by Django 5.2.6 on 2025-11-02 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_user_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproposalupload',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_feedbacks/'),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('needs_review', 'نیاز به بازبینی')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'title')},
            },
        ),
        migrations.CreateModel(
            name='UserCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.userproposalupload')),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Accounts.usercategory')),
            ],
            options={
                'unique_together': {('user_category', 'file')},
            },
        ),
    ]
