# Generated by Django 5.2.6 on 2025-11-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_usercategoryitem_priority_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consultant_admin',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، کاربر همزمان نقش مشاور و ادمین دارد.'),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='font_path',
            field=models.CharField(blank=True, help_text='مسیر کامل فونت برای خروجی PDF یا Word', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='is_downloadable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproposalupload',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
