# Generated by Django 5.2.6 on 2025-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_user_is_consultant_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
