# Generated by Django 5.2.6 on 2025-10-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_alter_proposal_options_alter_proposalimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestiontext',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='suggestiontext',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suggestiontext',
            name='trigger_keyword',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
