# Generated by Django 5.2.6 on 2025-10-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0005_proposalaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='proposal_previews/'),
        ),
    ]
