# Generated by Django 5.2.6 on 2025-11-04 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0006_proposal_preview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalGuidebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('guidebook_file', models.FileField(upload_to='guidebooks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidebooks', to='suggestion.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('roadmap_file', models.FileField(upload_to='roadmaps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='suggestion.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalSampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sample_file', models.FileField(upload_to='samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='suggestion.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='suggestion.proposal')),
            ],
        ),
    ]
