# Generated by Django 5.2.6 on 2025-11-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0007_proposalguidebook_proposalroadmap_proposalsamplefile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
