# Generated by Django 5.2.6 on 2025-11-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
